### ISSUE TITLE
Confluence Session not created - DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by jlriverayuso** [WikiTransformationProject/wikitraccs-releases#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i click start transformation and the console tries to test my Confluence connection I immediately get:
![DevToolsActivePort file doesn't exist](https://github.com/user-attachments/assets/743560ab-e6dc-4d57-b003-0d81f795acab)

i do want to add that Chrome does open

### Expected Behavior

Chrome should open and go to Confluence. 

### WikiTraccs Version

v1.18.15

### Confluence Version

Confluence 6

### Confluence Data Center?

- [ ] This is about Confluence Data Center

### Relevant log output or page storage format

```shell
[ 07:59:59 DBG] Receiving activity Testing endpoint connectivity... with percent 0 and type "Processing" | 
[ 07:59:59 DBG] Entering CheckConnectionsAsync, checking categories "ChromeWebDriverCheckAndDownload" | 
[ 07:59:59 DBG] Checking connection to https://chromedriver.storage.googleapis.com by reading string response... | 
[ 07:59:59 DBG] HTTP result for https://chromedriver.storage.googleapis.com (first 300 chars): <?xml version='1.0' encoding='UTF-8'?><ListBucketResult xmlns='http://doc.s3.amazonaws.com/2006-03-01'><Name>chromedriver</Name><Prefix></Prefix><Marker></Marker><IsTruncated>false</IsTruncated><Contents><Key>100.0.4896.20/chromedriver_linux64.zip</Key><Generation>1646371839854073</Generation><MetaG | 
[ 07:59:59 DBG] Set isConnectionCheckSuccessful to: true | 
[ 07:59:59 DBG] Checking connection to https://chromedriver.chromium.org by reading string response... | 
[ 08:00:00 DBG] HTTP result for https://chromedriver.chromium.org (first 300 chars): <!doctype html>
<html 
      lang="en"
      dir="ltr">
  <head>
    <meta name="google-signin-client-id" content="157101835696-ooapojlodmuabs2do2vuhhnf90bccmoi.apps.googleusercontent.com">
    <meta name="google-signin-scope"
          content="profile email https://www.googleapis.com/auth/develope | 
[ 08:00:00 DBG] Set isConnectionCheckSuccessful to: true | 
[ 08:00:00 DBG] Checking connection to https://googlechromelabs.github.io/chrome-for-testing by reading string response... | 
[ 08:00:00 DBG] HTTP result for https://googlechromelabs.github.io/chrome-for-testing (first 300 chars): <!DOCTYPE html><html lang=en><meta charset=utf-8><title>Chrome for Testing availability</title><meta content="width=device-width" name=viewport><style>html{font:1rem/1.6 sans-serif}::selection{background:#1e90ff;color:#fff}.table-wrapper{overflow-x:auto}@media (width >= 60rem){.summary{font-size:2re | 
[ 08:00:00 DBG] Set isConnectionCheckSuccessful to: true | 
[ 08:00:00 DBG] Checking connection to https://edgedl.me.gvt1.com by reading string response... | 
[ 08:00:01 DBG] HTTP result for https://edgedl.me.gvt1.com (first 300 chars): <!DOCTYPE html>
                            <script nonce="WW47mpTec58xDsxJ_-nlUQ">
  function r(p){try{window.stop();}catch(exception){document.execCommand('Stop');}window.location.replace(p+window.location.search)}var ua=navigator.userAgent;if(ua.match(".*NT 5\.[12].*")!==null){ r("/chrome/fallbac | 
[ 08:00:01 DBG] Set isConnectionCheckSuccessful to: true | 
[ 08:00:01 DBG] Checking connection to https://storage.googleapis.com/chrome-for-testing-public by reading string response... | 
[ 08:00:01 INF] Got HttpRequestException: Response status code does not indicate success: 403 (Forbidden). (Status code: "Forbidden") - will check if still ok | 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at WikiTraccs.Shared.SanityChecks.PrerequisiteChecks.CheckConnectionsAsync(UrlCategory categories, Boolean exitWithFirstFailedConnection, UrlToCheck[] additionalUrls) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/ProcessedObjects/ProcessedConfluenceUser.cs:line 199
[ 08:00:01 DBG] Successful check for connection (got expected "Forbidden" result for 'https://storage.googleapis.com/chrome-for-testing-public', set isConnectionCheckSuccessful to: true) | 
[ 08:00:01 DBG] Returning connection check result: [{"UrlToCheck":{"Url":{"Scheme":"https","UserInfo":"","Host":"chromedriver.storage.googleapis.com","Port":null,"Authority":"chromedriver.storage.googleapis.com","Root":"https://chromedriver.storage.googleapis.com","Path":"","PathSegments":[],"Query":"","QueryParams":[],"Fragment":"","IsRelative":false,"IsSecureScheme":true},"Category":1,"UsedFor":"downloading the web driver for your current Chrome version","IsOptional":true},"IsConnectionCheckSuccessful":true},{"UrlToCheck":{"Url":{"Scheme":"https","UserInfo":"","Host":"chromedriver.chromium.org","Port":null,"Authority":"chromedriver.chromium.org","Root":"https://chromedriver.chromium.org","Path":"","PathSegments":[],"Query":"","QueryParams":[],"Fragment":"","IsRelative":false,"IsSecureScheme":true},"Category":1,"UsedFor":"checking which web driver version is needed for your current Chrome version","IsOptional":true},"IsConnectionCheckSuccessful":true},{"UrlToCheck":{"Url":{"Scheme":"https","UserInfo":"","Host":"googlechromelabs.github.io","Port":null,"Authority":"googlechromelabs.github.io","Root":"https://googlechromelabs.github.io","Path":"/chrome-for-testing","PathSegments":["chrome-for-testing"],"Query":"","QueryParams":[],"Fragment":"","IsRelative":false,"IsSecureScheme":true},"Category":1,"UsedFor":"checking which web driver version is needed for your current Chrome version","IsOptional":true},"IsConnectionCheckSuccessful":true},{"UrlToCheck":{"Url":{"Scheme":"https","UserInfo":"","Host":"edgedl.me.gvt1.com","Port":null,"Authority":"edgedl.me.gvt1.com","Root":"https://edgedl.me.gvt1.com","Path":"","PathSegments":[],"Query":"","QueryParams":[],"Fragment":"","IsRelative":false,"IsSecureScheme":true},"Category":1,"UsedFor":"checking which web driver version is needed for your current Chrome version","IsOptional":true},"IsConnectionCheckSuccessful":true},{"UrlToCheck":{"Url":{"Scheme":"https","UserInfo":"","Host":"storage.googleapis.com","Port":null,"Authority":"storage.googleapis.com","Root":"https://storage.googleapis.com","Path":"/chrome-for-testing-public","PathSegments":["chrome-for-testing-public"],"Query":"","QueryParams":[],"Fragment":"","IsRelative":false,"IsSecureScheme":true},"Category":1,"UsedFor":"checking which web driver version is needed for your current Chrome version","IsOptional":true},"IsConnectionCheckSuccessful":true}] | 
[ 08:00:01 DBG] Leaving CheckConnectionsAsync | 
[ 08:00:01 DBG] Receiving activity Testing endpoint connectivity... with percent 0 and type "Completed" | 
[ 08:00:01 DBG] Creating instance | WikiTraccs.Shared.ConfluenceInternal.ConfluenceInternalApiAccessor.ConfluenceHttpClientFactory
[ 08:00:01 DBG] Creating instance | WikiTraccs.Shared.Automation.ConfluenceSessionIdRetriever
[ 08:00:01 DBG] Receiving activity Launching browser, waiting for Confluence login... with percent 0 and type "Processing" | 
[ 08:00:01 DBG] Looking for cookie override file at 'C:\Users\riveraayusoj\OneDrive - SEC\OIT\EDT Migration\WikiTraccs_1.18.15_windows_x64_release_selfcontained\WikiTraccs.GUI\cookies.txt'... | 
[ 08:00:01 DBG] No file present. | 
[ 08:00:01 DBG] [https://confluence.ad.sec.gov/] Trying to log into Confluence, Config: {"TenantId":"https://confluence.ad.sec.gov/","AuthenticationType":"cookie","PersonalAccessToken":"","BasicAuthUsername":"","HumanReadableId":"https://confluence.ad.sec.gov/","AuthCookieNames":[""],"PageIdIncludeList":[],"PageIdForLiveUpdate":null,"ReprocessContentWithErrors":false,"SpaceTransfer":{"Enabled":true,"SpaceIncludeList":[],"ForceReprocess":null,"Operations":["retrievecontents"],"$type":"SpaceTransfer"},"PermissionTransfer":{"Enabled":false,"SpaceIncludeList":[],"ForceReprocess":null,"$type":"PermissionTransfer"},"BaseUrl":"https://confluence.ad.sec.gov/","AuthUrl":"","$type":"SourceTenantConfiguration"} | WikiTraccs.Shared.Automation.ConfluenceSessionIdRetriever
[ 08:00:01 DBG] Trying to determine Chrome version to get the right driver for | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Reading Chrome binary path from registry path 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe' | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Chrome binary path 'C:\Program Files\Google\Chrome\Application\chrome.exe' found in registry and verified | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Chrome version: 127.0.6533.73 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Got Chrome major version 127 from chrome version number 127.0.6533 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Determining web driver version from 3-number Chrome version '127.0.6533' from URL https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json... | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Got web driver version: 127.0.6533.72 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Target directory for web driver: C:\Users\riveraayusoj\OneDrive - SEC\OIT\EDT Migration\WikiTraccs_1.18.15_windows_x64_release_selfcontained\WikiTraccs.GUI | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:01 DBG] Found existing web driver, checking version... | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:02 DBG] Existing web driver version: ChromeDriver 127.0.6533.72 (9755e24ca85aa18ffa16c743f660a3d914902775-refs/branch-heads/6533@{#1760})
 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:02 DBG] Existing web driver version is up to date: 127.0.6533.72 | WikiTraccs.Shared.Misc.ChromeDriverInstaller
[ 08:00:02 DBG] [https://confluence.ad.sec.gov/] Storing Chrome profile in 'C:\Users\riveraayusoj\AppData\Local\Temp\1\WikiTraccs\https___confluence.ad.sec.gov' | WikiTraccs.Shared.Automation.ConfluenceSessionIdRetriever
[ 08:00:04 ERR] Showing message box: Failure ### Error while preparing and launching browser for Confluence login: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated) | 
[ 08:00:08 DBG] Receiving activity Launching browser, waiting for Confluence login... with percent 0 and type "Completed" |
```

**Comment by heinrich-ulbricht** [comment]
@jlriverayuso Did that work with a previous version of WikiTraccs and started to happen recently? Does it happen on all machines WikiTraccs runs on? Could you try running it on another machine?

Are you running WikiTraccs as admin? Can you try running it not as admin, please?

Trying to figure out what might be causing this.

**Comment by heinrich-ulbricht** [comment]
I added a setting to WikiTraccs that might help with this error, based on reports in the Chrome development forums.

@jlriverayuso If the error persists, could you please try this preview release and set the checkbox shown in the screenshot over here -> https://github.com/WikiTransformationProject/wikitraccs-releases/releases/tag/v1.18.19

**Comment by jlriverayuso** [comment]
@heinrich-ulbricht  I just tried the new version, i get this message when i try to start the transformation.

![image](https://github.com/user-attachments/assets/6dc53663-3713-40ca-995f-c18f29e12a66)


another thing i did see is that if i try to test the connections, the GUI just force closes.

**Comment by jlriverayuso** [comment]
@heinrich-ulbricht just sent it your way.

**Comment by heinrich-ulbricht** [comment]
Note: the issue is being investigated and most likely related to a TLS protocol mismatch of client and server. Updates will follow.

**Comment by heinrich-ulbricht** [comment]
Update: the issue is related to TLS 1.3. A workaround has been activated. A blog post with details will follow.
