### ISSUE TITLE
WikiTracs exception

### ISSUE THREAD

**Issue by Alin-Dumitrescu** [WikiTransformationProject/wikitraccs-releases#49]
Hello,

I am evaluating WikiTracs for a confluence site migration to SharePoint. I am getting the following error in the log - how do we fix it?

Thanks, Alin

[036 01:22:19 WRN 331773582 sre] [https://confluence.bbpd.io] Got an error, applying again without files and and only an empty page (error: Microsoft.SharePoint.Client.ServerException: The specified user **first.last@domain.com** could not be found.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent) in /_/src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs:line 172
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent) in /_/src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs:line 97
   at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ListItemUtilities.UpdateListItem(ListItem item, TokenParser parser, IDictionary`2 valuesToSet, ListItemUpdateType updateType, Boolean SkipExecuteQuery) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs:line 408
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectFiles.SetFileProperties(File file, IDictionary`2 properties, TokenParser parser, Boolean checkoutIfRequired) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectFiles.cs:line 347
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectFiles.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectFiles.cs:line 228
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs:line 455
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.<>c__DisplayClass16_1.sNXrpbdp3R()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.ApplyProvisioningTemplateAsync(ConfluenceDataContext cfContext, PnPContext pnpContext, ProvisioningTemplate provisioningTemplate, CancellationToken cancellationToken)
   at WikiTraccs.Console.Stores.SPO.SpoContentStore.StoreInSpoAsync(TransformationContext trafoCtx, ProvisioningRequest provisioningRequest, CancellationToken cancellationToken)
   at WikiTraccs.Console.Registries.ConfluenceContentRegistry.StoreInSpoAsync(TransformationContext trafoCtx, ProvisioningRequest provisioningRequest, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/Registries/ConfluenceUserRegistry.cs:line 139) | WikiTraccs.Console.Registries.ConfluenceContentRegistry

**Comment by Alin-Dumitrescu** [comment]
We do not have a user mapping and the user doesn’t exist in the destination. We have likely hundred of users that do not exist and the expectation would be that the pages would be migrated without that info or using a default account. But the error message says the pages are created empty...

Thank you,
Alin Dumitrescu
Azure DevOps Consultant
phone (425) 279-3465

**Comment by heinrich-ulbricht** [comment]
@Alin-Dumitrescu I'll schedule a release for next week that handles such users differently.

**Comment by Alin-Dumitrescu** [comment]
Thank you Heinrich,

What about the other issue with the flat entries in the tree page = any thoughts what the problem is?

Thank you,
Alin Dumitrescu
Azure DevOps Consultant
phone (425) 279-3465

**Comment by heinrich-ulbricht** [comment]
@Alin-Dumitrescu The [latest release v1.3.7](https://github.com/WikiTransformationProject/wikitraccs-releases/releases) should show a different behavior regarding unresolved user accounts. Please delete all empty placeholder pages in SharePoint and start another Confluence to SharePoint migration. It should now succeed to create the page.

(I'll hop over to #48 for the page tree issue.)
