### ISSUE TITLE
[Bug] Error while preparing site: Scope of template does not match target

### ISSUE THREAD

**Issue by PretoPlasma** [WikiTransformationProject/wikitraccs-releases#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whilst running migration preperation steps the WikiTraccs.Console throws the following System.Exception:

Scope of template does not match target
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs:line 322
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in /_/src/lib/PnP.Framework/Extensions/WebExtensions.cs:line 1182
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.<>c__DisplayClass17_1.BlcIIGOv49()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.ApplyProvisioningTemplateAsync(ConfluenceDataContext cfContext, PnPContext pnpContext, ProvisioningTemplate provisioningTemplate, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.PrepareTargetSiteInternalAsync(SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/SpoWikiTraccsStore.cs:line 24
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.PrepareTargetSiteAsync(SpoCheckResult checkResult, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.PrepareTargetAsync(IPreparableTarget target, SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 30
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.PrepareTargetAsync(IPreparableTarget target, SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 30
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.EnsureSitePreparationAsync(IPreparableTarget target, TransformationContext trafoCtx, Func`1 shallPrepareCallback, Boolean throwOnFailure, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 25

### Expected Behavior

I would expect to get smoothly through WikiTraccs.Console migration preparation steps without any exception throwing. ;-)

### WikiTraccs Version

v1.7.4

### Confluence Version

Confluence 7 (up to 7.17)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

### Relevant log output or page storage format

```shell
[009 12:48:28 DBG  ] [https://CONFLUENCESERVER] Checking that destination SharePoint site is prepared: https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop ... | WikiTraccs.Shared.Stores.SPO.StorePreparator
[009 12:48:28 DBG  ] Entering CreatePnPContext... | WikiTraccs.Shared.Stores.SPO.PnPContextFactory
[009 12:48:32 DBG  ] Leaving CreatePnPContext... | WikiTraccs.Shared.Stores.SPO.PnPContextFactory
[009 12:48:32 DBG  ] [https://CONFLUENCESERVER] Getting provisioning template from 'D:\Programme\WikiTraccs.Console\Stores\SPO' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[009 12:48:33 DBG  ] [https://CONFLUENCESERVER] Found 5 templates | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[009 12:48:33 INF  ] [https://CONFLUENCESERVER] DONE: Checking that destination SharePoint site is prepared; Result=false | WikiTraccs.Shared.Stores.SPO.StorePreparator
[009 12:48:33 INF  ] [https://CONFLUENCESERVER] Preparing site (this has to be done once for a site)... | WikiTraccs.Shared.Stores.SPO.StorePreparator
[009 12:48:33 DBG  ] Entering CreatePnPContext... | WikiTraccs.Shared.Stores.SPO.PnPContextFactory
[009 12:48:33 DBG  ] Leaving CreatePnPContext... | WikiTraccs.Shared.Stores.SPO.PnPContextFactory
[007 12:48:34 DBG  ] [https://CONFLUENCESERVER] Trying to create list 'WikiTraccs Locks'... | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:34 DBG  ] [https://CONFLUENCESERVER] DONE: Creating list 'WikiTraccs Locks'... | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:35 DBG  ] [https://CONFLUENCESERVER] Making sure Title has EnforceUniqueValues set on list 'WikiTraccs Locks'... | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:35 DBG  ] [https://CONFLUENCESERVER] DONE: Making sure Title has EnforceUniqueValues set on list 'WikiTraccs Locks' | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:35 DBG  ] [https://CONFLUENCESERVER] Trying to set lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Successfully set lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' with ID 1 | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Preparing target site '"https://SHAREPOINTSITE/EMO - Werbemanager - Webshop"', found 1 templates to apply (reason: Cannot find view 'Spaces Metadata' on Confluence Space Inventory (WikiTraccs) list) | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Getting provisioning template from 'D:\Programme\WikiTraccs.Console\Stores\SPO' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Found 5 templates | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Applying template 'TEMPLATE-WikiTraccsSite_ConfluenceSpaceInventory' to site '"https://SHAREPOINTSITE/EMO - Werbemanager - Webshop"' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Applying provisioning template to web... | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[011 12:48:36 ERR  ] [Provisioning] Scope of template does not match target 349ms 205c0927-a9dd-4aca-8b33-501a2e893635 | WikiTraccs.Console.Program
[011 12:48:36 DBG  ] [https://CONFLUENCESERVER] DONE: Applying provisioning template to web | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Removing lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' (1) | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:36 DBG  ] [https://CONFLUENCESERVER] Deleting lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' item with ID 1 | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:37 DBG  ] [https://CONFLUENCESERVER] DONE: Deleting lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' item with ID 1 | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:37 ERR  ] [https://CONFLUENCESERVER] Error while preparing site: Scope of template does not match target | WikiTraccs.Shared.Stores.SPO.StorePreparator
System.Exception: Scope of template does not match target
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs:line 322
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in /_/src/lib/PnP.Framework/Extensions/WebExtensions.cs:line 1182
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.<>c__DisplayClass17_1.BlcIIGOv49()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.ApplyProvisioningTemplateAsync(ConfluenceDataContext cfContext, PnPContext pnpContext, ProvisioningTemplate provisioningTemplate, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.PrepareTargetSiteInternalAsync(SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/SpoWikiTraccsStore.cs:line 24
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.PrepareTargetSiteAsync(SpoCheckResult checkResult, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.PrepareTargetAsync(IPreparableTarget target, SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 30
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.PrepareTargetAsync(IPreparableTarget target, SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 30
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.EnsureSitePreparationAsync(IPreparableTarget target, TransformationContext trafoCtx, Func`1 shallPrepareCallback, Boolean throwOnFailure, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 25
[007 12:48:37 DBG  ] [https://CONFLUENCESERVER] Checking again that destination SharePoint site is prepared (this should now succeed): https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop ... | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:37 DBG  ] [https://CONFLUENCESERVER] Getting provisioning template from 'D:\Programme\WikiTraccs.Console\Stores\SPO' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:37 DBG  ] [https://CONFLUENCESERVER] Found 5 templates | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:37 INF  ] [https://CONFLUENCESERVER] DONE: Checking that destination SharePoint site is prepared; Result=false | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:37 WRN  ] [https://CONFLUENCESERVER] Even after preparing the site the preparation check for https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop fails; this needs to be... checked; Errors: ["Cannot find view 'Spaces Metadata' on Confluence Space Inventory (WikiTraccs) list"] | WikiTraccs.Shared.Stores.SPO.StorePreparator
[011 12:48:37 DBG  ] [https://CONFLUENCESERVER] Checking that destination SharePoint site is prepared: https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop ... | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:37 DBG  ] [https://CONFLUENCESERVER] Done handling retrieval request for tenant from stream (reason: 'calling from TokenStore_OnTokenRenewalFinished') | WikiTraccs.Console.ConfluenceMonitors.ConfluencePermissionRetriever
[011 12:48:37 DBG  ] [https://CONFLUENCESERVER] Getting provisioning template from 'D:\Programme\WikiTraccs.Console\Stores\SPO' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:37 ERR  ] [https://CONFLUENCESERVER] Unhandled exception in subscription of AttachToRequestPipeline->scanRequestObservable | WikiTraccs.Console.ConfluenceMonitors.ConfluencePermissionRetriever
WikiTraccs.Shared.Interfaces.WikiTraccsSiteNotPreparedException: Failed to prepare site 'https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop'. Cannot work if prerequisites are missing. Normally I am able to create _and_ verify them, but something happened.
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.EnsureSitePreparationAsync(IPreparableTarget target, TransformationContext trafoCtx, Func`1 shallPrepareCallback, Boolean throwOnFailure, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 25
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.EnsureSiteIsPrepared(TransformationContext trafoCtx, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore.GetSpaceInventoryForTenantAsync(TransformationContext trafoCtx, Boolean onlyWithTrafoRequest, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Registries.WikiTraccsRegistry.GetSpaceInventoryForTenantAsync(TransformationContext trafoCtx, Boolean onlyWithTrafoRequest, Boolean ignoreCache, CancellationToken cancellationToken)
   at WikiTraccs.Console.ConfluenceMonitors.ConfluencePermissionRetriever.EnqueueRetrievalAsync(TransformationContext trafoCtx, RetrievalMode mode, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/ConfluenceMonitors/RetrieverBase.cs:line 44
   at WikiTraccs.Console.ConfluenceMonitors.RetrieverBase`2.<>c__DisplayClass53_0.vqx9q52woTJTiQ679VS.MoveNext() in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/API/TheConfluenceCloudRestAPIClient.cs:line 118
[011 12:48:37 DBG  ] [https://CONFLUENCESERVER] Found 5 templates | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[011 12:48:37 INF  ] [https://CONFLUENCESERVER] DONE: Checking that destination SharePoint site is prepared; Result=false | WikiTraccs.Shared.Stores.SPO.StorePreparator
[011 12:48:37 INF  ] [https://CONFLUENCESERVER] Preparing site (this has to be done once for a site)... | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Trying to set lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Successfully set lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' with ID 2 | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Preparing target site '"https://SHAREPOINTSITE/EMO - Werbemanager - Webshop"', found 1 templates to apply (reason: Cannot find view 'Spaces Metadata' on Confluence Space Inventory (WikiTraccs) list) | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Getting provisioning template from 'D:\Programme\WikiTraccs.Console\Stores\SPO' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Found 5 templates | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Applying template 'TEMPLATE-WikiTraccsSite_ConfluenceSpaceInventory' to site '"https://SHAREPOINTSITE/EMO - Werbemanager - Webshop"' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Applying provisioning template to web... | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[011 12:48:38 ERR  ] [Provisioning] Scope of template does not match target 213ms 7f45c98d-ca60-464c-a27b-ae03cdb1b784 | WikiTraccs.Console.Program
[011 12:48:38 DBG  ] [https://CONFLUENCESERVER] DONE: Applying provisioning template to web | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:38 DBG  ] [https://CONFLUENCESERVER] Removing lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' (2) | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:39 DBG  ] [https://CONFLUENCESERVER] Deleting lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' item with ID 2 | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:39 DBG  ] [https://CONFLUENCESERVER] DONE: Deleting lock 'LOCK: WikiTraccs is preparing the site-https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop_10678370987995173465' item with ID 2 | WikiTraccs.Shared.Stores.SPO.SpoLock
[007 12:48:39 ERR  ] [https://CONFLUENCESERVER] Error while preparing site: Scope of template does not match target | WikiTraccs.Shared.Stores.SPO.StorePreparator
System.Exception: Scope of template does not match target
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) in /_/src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs:line 322
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in /_/src/lib/PnP.Framework/Extensions/WebExtensions.cs:line 1182
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.<>c__DisplayClass17_1.BlcIIGOv49()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.ApplyProvisioningTemplateAsync(ConfluenceDataContext cfContext, PnPContext pnpContext, ProvisioningTemplate provisioningTemplate, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.PrepareTargetSiteInternalAsync(SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/SpoWikiTraccsStore.cs:line 24
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.PrepareTargetSiteAsync(SpoCheckResult checkResult, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.PrepareTargetAsync(IPreparableTarget target, SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 30
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.PrepareTargetAsync(IPreparableTarget target, SpoCheckResult checkResult, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 30
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.EnsureSitePreparationAsync(IPreparableTarget target, TransformationContext trafoCtx, Func`1 shallPrepareCallback, Boolean throwOnFailure, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 25
[007 12:48:39 DBG  ] [https://CONFLUENCESERVER] Checking again that destination SharePoint site is prepared (this should now succeed): https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop ... | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:39 DBG  ] [https://CONFLUENCESERVER] Getting provisioning template from 'D:\Programme\WikiTraccs.Console\Stores\SPO' | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:39 DBG  ] [https://CONFLUENCESERVER] Found 5 templates | WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore
[007 12:48:39 INF  ] [https://CONFLUENCESERVER] DONE: Checking that destination SharePoint site is prepared; Result=false | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:39 WRN  ] [https://CONFLUENCESERVER] Even after preparing the site the preparation check for https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop fails; this needs to be... checked; Errors: ["Cannot find view 'Spaces Metadata' on Confluence Space Inventory (WikiTraccs) list"] | WikiTraccs.Shared.Stores.SPO.StorePreparator
[007 12:48:39 DBG  ] [https://CONFLUENCESERVER] Done handling retrieval request for tenant from stream (reason: 'calling from TokenStore_OnTokenRenewalFinished') | WikiTraccs.Console.ConfluenceMonitors.ConfluenceContentRetriever
[007 12:48:39 ERR  ] [https://CONFLUENCESERVER] Unhandled exception in subscription of AttachToRequestPipeline->scanRequestObservable | WikiTraccs.Console.ConfluenceMonitors.ConfluenceContentRetriever
WikiTraccs.Shared.Interfaces.WikiTraccsSiteNotPreparedException: Failed to prepare site 'https://SHAREPOINTSITE/EMO%20-%20Werbemanager%20-%20Webshop'. Cannot work if prerequisites are missing. Normally I am able to create _and_ verify them, but something happened.
   at WikiTraccs.Shared.Stores.SPO.StorePreparator.EnsureSitePreparationAsync(IPreparableTarget target, TransformationContext trafoCtx, Func`1 shallPrepareCallback, Boolean throwOnFailure, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Shared/Stores/SPO/TransformedPageInfo.cs:line 25
   at WikiTraccs.Shared.Stores.SPO.SpoStoreBase.EnsureSiteIsPrepared(TransformationContext trafoCtx, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Stores.SPO.SpoWikiTraccsStore.GetSpaceInventoryForTenantAsync(TransformationContext trafoCtx, Boolean onlyWithTrafoRequest, CancellationToken cancellationToken)
   at WikiTraccs.Shared.Registries.WikiTraccsRegistry.GetSpaceInventoryForTenantAsync(TransformationContext trafoCtx, Boolean onlyWithTrafoRequest, Boolean ignoreCache, CancellationToken cancellationToken)
   at WikiTraccs.Console.ConfluenceMonitors.ConfluenceContentRetriever.EnqueueRetrievalAsync(TransformationContext trafoCtx, RetrievalMode modeOBSOLETEDONOTUSE, CancellationToken cancellationToken) in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/ConfluenceMonitors/ConfluencePermissionsRetriever.cs:line 479
   at WikiTraccs.Console.ConfluenceMonitors.RetrieverBase`2.<>c__DisplayClass53_0.vqx9q52woTJTiQ679VS.MoveNext() in /home/runner/work/wikitraccs-code/wikitraccs-code/WikiTraccs.Console/API/TheConfluenceCloudRestAPIClient.cs:line 118
```

### Anything else?

We run WikiTraccs.Console wrapped around an RPA-Robot driven by appsettings.json only.

**Comment by heinrich-ulbricht** [comment]
@PretoPlasma Are you by any chance trying to migrate to a subsite? The error message looks like the one in #39. Migration is only supported to the root of SharePoint site collections.

**Comment by PretoPlasma** [comment]
@heinrich-ulbricht That's the case. Thanks for your confirmation. Much appreciated! Then we are going to change our migration target. You can close this one! :-)
